-- MySQL Script generated by MySQL Workbench
-- Sun Oct 17 20:39:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TUS_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TUS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TUS_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `TUS_DB` ;

-- -----------------------------------------------------
-- Table `TUS_DB`.`CV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TUS_DB`.`CV` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(2000) NOT NULL,
  `rating` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TUS_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TUS_DB`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `location` VARCHAR(30) NULL DEFAULT NULL,
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `photo` VARCHAR(50) NULL DEFAULT NULL,
  `role` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id`)
    REFERENCES `TUS_DB`.`CV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TUS_DB`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TUS_DB`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NOT NULL,
  `state` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Reviews_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `TUS_DB`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TUS_DB`.`Sybject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TUS_DB`.`Sybject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `CV_id` INT NOT NULL,
  PRIMARY KEY (`id`, `CV_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Sybject_CV1_idx` (`CV_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sybject_CV1`
    FOREIGN KEY (`CV_id`)
    REFERENCES `TUS_DB`.`CV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
